<input type="button" name="google_button" id="send_not" value="Send Notification">


<script type="text/javascript">  
(function  () {    
    require(["jquery"], function($) {
        $(document).ready(function($) {
            $("#send_not").on("click", function(e){
                                
               var url = "https://api.prod.unirsal.com/backend-service/v3/whatsapp-session/message"

                $.ajax({
                    url: url,
                        type: 'post',
                        headers: {
                              'Authorization': $('#whatsappbasic_moduleoption_apikey').val()
                          },

                        data: {
                            
                         "type": "text",
                         "sessionId": $('#whatsappbasic_moduleoption_id').val(),
                         "recipientPhone": $('#whatsappbasic_moduleoption_test_phone').val(),
                          "text": {
                                  "message": $('#whatsappbasic_moduleoption_test_template').val()
                          }
 
                         }
                         dataType: 'json',
                         success: function (data) {
                                console.info(data);
                                 alert('notification Sent')
                        }
                });
            })
        }); 
    });
})();
</script>
